@0xfb0c1cad58b9701d;   # Unique ID; Generated by `capnp id`
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("poplar::cap");

using SerialiserPrograms = import "Program.capnp";
using SerialiserPrograms.Programs;

using SerialiserGraph = import "CoreGraph.capnp";
using SerialiserGraph.CoreGraph;

struct Serialiser {
  programs @0 :Programs;
  coreGraph @1: CoreGraph;
}
