@0xdd6977a79018777c; # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("poplar::cap");

struct TargetInfo {
  numIPUs @0 :UInt32;
  # TODO: This is currently not set due to complications related to virtual
  # targets.
  tilesPerIPU @1 :UInt32;
  memoryBytesPerTile @2 :UInt32;
  numWorkerContexts @3 :UInt32;
  memoryElementOffsets @4 :List(UInt32);
  memoryElementInterleavedIndex @5 :UInt32;
}
